### ISSUE TITLE
React hook 

### ISSUE THREAD

**Issue by youminkim** [statsig-io/statsig-feedback#1]
Hi, thanks for great service. I just started using Statsig in https://take.app 
Our service is written in React and most of my components are functions. Hook such as `useStatsig()`  would be useful. 

This is my code example:
```
    const [statsigReady, setStatsigReady] = useState(false)
    useEffect(()=>{
        async function f() {
            await statsig.initialize(
                "CLIENT KEY", 
                {custom: {
                    tier: shop_tier,
                    shopCountry: shop_country,
                }});
        }
        f().then(()=>{
            setStatsigReady(true)
        })
    }, [])

...
 <Placement isReady={statsigReady}/>
```

```
export default function Placement({
    isReady,
}) {

    if(!statsig.isReady()) return null
    
    if (statsig.checkGate("adsense")) { ... }

}
```

**Comment by roim** [comment]
Hi Youmin!

Thanks for the idea, we *are* planning to build framework utilities and React is on the list (we also use it in our apps, eg on console.statsig.com). I'll chat with the team tomorrow and see if someone can pick it up this week.

**Comment by tore-statsig** [comment]
Hey Youmin!

Thanks for the feedback.  We will update the SDK with better support for React this week.

**Comment by tore-statsig** [comment]
Okay nothing finalized yet, but I published a pre-release version of the SDK, and a public github repo:

https://github.com/statsig-io/react-sdk

https://www.npmjs.com/package/statsig-react-pre-release

Feel free to poke around if you are interested, and comment back here if you have feedback.  This is under active development, but wanted to share since there has been meaningful enough progress

**Comment by tore-statsig** [comment]
The react SDK has been published!

https://docs.statsig.com/client/reactSDK

https://www.npmjs.com/package/statsig-react

https://github.com/statsig-io/react-sdk
