### ISSUE TITLE
Role Based Access Control on Individual Created Feature Gates Or Rules in Statsig

### ISSUE THREAD

**Issue by prashantagrawal3108** [statsig-io/statsig-feedback#40]
Is it Possible to have Role based Edit/Delete access on individual Feature Gates Or Rules in Statsig?

**Example:-**

Suppose I want to implement that "user-1" **should not** be able to Edit/Delete "Feature-Gate-1" or "Rule-1" in "Feature-Gate-1", but **should** be able to edit/delete other Feature Gates or Rules in the same Project.

Please let me know, if this is possible in statsig. Or is there any plan in future to consider this feature?

**Comment by vijaye-statsig** [comment]
Update: we do have entity level reviews that you can turn on so not everyone can arbitrarily ship new things. You can read more here: https://docs.statsig.com/guides/setting-up-reviews#enforcing-team-reviews

We don’t support it at the rulesets level. Thinking about it a bit, that would be tricky because any ruleset ahead of the locked one could override or render the locked one useless. 

old text: Thanks for your feature request. Entity level access control is not currently supported and we don’t have plans to add it for now.

**Comment by prashantagrawalcrowe** [comment]
I was going through this feature, and I did not get the option for "Allow Project Admins to self-approve reviews " under "Config Review Requirements". Can you help me with this option?
