### ISSUE TITLE
Why are checkGate and getConfig asynchronous?

### ISSUE THREAD

**Issue by twk** [statsig-io/statsig-feedback#5]
In a past job, unpredictable performance from our feature gating library was an ongoing nightmare. When I see that checkGate and getConfig are asynchronous, it makes me worry that you might be making HTTP calls under the hood (as opposed to loading all the rules ahead of time).  Can you tell me what's going on in there?

Thanks!

**Comment by jkw-statsig** [comment]
Great question @twk! We are indeed loading all the rules at initialization ahead of time and evaluating them **without** making http calls (you can take a look at our [evaluation code here](https://github.com/statsig-io/node-js-server-sdk/blob/main/src/Evaluator.js#L110) if you are curious). The checkGate and getConfig APIs in our server SDKs are only async because we are trying to make the current SDKs more future proof and able to fetch the values from our server **in case in the future we introduce new rule conditions that older version of SDKs do not know how to evaluate**.

Hope that helps and let me know if you have more questions or suggestions!

**Comment by twk** [comment]
That makes sense, thank you!

**Comment by roim** [comment]
> That makes sense, thank you!

@twk If the SDK finds a condition it doesn't yet know how to evaluate, we could return a default value instead of going through a network request. We'll have that as an option eventually, if it's important for you let us know and we can bump its priority.

**Comment by roim** [comment]
I added an explanation to our server sdk docs. Thanks again for bringing this up
